"""init

Revision ID: bbd1e315688c
Revises: 
Create Date: 2026-03-24 23:47:29.748112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbd1e315688c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('winning_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_topics_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_title', sa.String(), nullable=False),
    sa.Column('source_data_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_action',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('situation', sa.String(), nullable=False),
    sa.Column('small_step_proposal', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_astrology',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('astrology_type', sa.String(), nullable=False),
    sa.Column('theme_or_symbol', sa.String(), nullable=False),
    sa.Column('fatalistic_meaning', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('is_seasonal', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.String(), nullable=True),
    sa.Column('valid_until', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_astrology_astrology_type'), 'knowledge_astrology', ['astrology_type'], unique=False)
    op.create_table('knowledge_copywriting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_type', sa.String(), nullable=False),
    sa.Column('suggested_text_pattern', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_empathy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('abstract_situation', sa.String(), nullable=False),
    sa.Column('empathy_approach', sa.Text(), nullable=False),
    sa.Column('warmth_level', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_mindfulness',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('philosophy_concept', sa.String(), nullable=False),
    sa.Column('encouragement_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_persona',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trait_name', sa.String(), nullable=False),
    sa.Column('trait_description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_reframing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('negative_state', sa.String(), nullable=False),
    sa.Column('positive_perspective', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worry_seeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_text_hash', sa.String(), nullable=False),
    sa.Column('abstract_worry', sa.Text(), nullable=False),
    sa.Column('source_tags', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worry_seeds_original_text_hash'), 'worry_seeds', ['original_text_hash'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note_url', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('used_knowledge_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['blog_topics_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_index(op.f('ix_worry_seeds_original_text_hash'), table_name='worry_seeds')
    op.drop_table('worry_seeds')
    op.drop_table('knowledge_reframing')
    op.drop_table('knowledge_persona')
    op.drop_table('knowledge_mindfulness')
    op.drop_table('knowledge_empathy')
    op.drop_table('knowledge_copywriting')
    op.drop_index(op.f('ix_knowledge_astrology_astrology_type'), table_name='knowledge_astrology')
    op.drop_table('knowledge_astrology')
    op.drop_table('knowledge_action')
    op.drop_table('blog_topics_candidates')
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
